### ISSUE TITLE
[enhancement] Support for resuming test execution after target crash

### ISSUE THREAD

**Issue by mazimkhan** [ARMmbed/utest#11]
utest and greentea can communicate test order and index. If target crashes greentea should be able to restart testing from the same index in same order.
Please #11 and https://github.com/ARMmbed/socket-test/issues/34

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2224

**Comment by niklas-arm** [comment]
See #16 for a proposal to add test case selection to the test setup handler.
