### ISSUE TITLE
missing {{__testcase_start;Basic}} in tests running on frdm-k64f-armcc (okay on frdm-k64f-gcc)

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/utest#19]
Error on all mbed-drivers tests running on frdm-k64f-armcc.  No errors on frdm-k64f-gcc.
Another person has reproduced this, so I am reporting it as a bug.  
Logs attached.
[test_fail_frdm-k64f-gcc.txt](https://github.com/ARMmbed/utest/files/239353/test_fail_frdm-k64f-gcc.txt)
[test_fail_frdm-k64f-armcc.txt](https://github.com/ARMmbed/utest/files/239354/test_fail_frdm-k64f-armcc.txt)

I have the following tools versions installed:
mbed-greentea (0.2.9)
mbed-host-tests (0.2.6)
mbed-ls (0.2.6)
mbed-test-wrapper (0.0.3)

Testing with mbed drivers 1.5.
C:\Users\maclob01\Documents\mbed-os\onsemi\mbed-drivers>yt ls
mbed-drivers 1.5.0
|_ mbed-hal 1.3.0 yotta_modules\mbed-hal
| _ mbed-hal-freescale 1.1.0 yotta_modules\mbed-hal-freescale
|   _ mbed-hal-ksdk-mcu 1.3.0 yotta_modules\mbed-hal-ksdk-mcu
|     |_ uvisor-lib 2.1.2 yotta_modules\uvisor-lib
|     _ mbed-hal-k64f 1.3.0 yotta_modules\mbed-hal-k64f
|       _ mbed-hal-frdm-k64f 1.1.1 yotta_modules\mbed-hal-frdm-k64f
|_ cmsis-core 1.2.0 yotta_modules\cmsis-core
| _ cmsis-core-freescale 1.1.0 yotta_modules\cmsis-core-freescale
|   _ cmsis-core-k64f 1.1.0 yotta_modules\cmsis-core-k64f
|_ ualloc 1.3.0
| _ dlmalloc 1.1.0 yotta_modules\dlmalloc
|_ minar 1.3.0
| _ minar-platform 1.1.0 yotta_modules\minar-platform
|   _ minar-platform-mbed 1.3.0 yotta_modules\minar-platform-mbed
|_ core-util 1.8.0
|_ compiler-polyfill 1.3.0
|_ greentea-client 1.1.0
_ unity 2.2.0 (test dependency)
  _ utest 1.12.2 yotta_modules\utest

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2510
