### ISSUE TITLE
utest does not allow for automated coverage reporting

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/utest#4]
The changes introduced to mbed-drivers [here to enable coverage reporting](https://github.com/ARMmbed/mbed-drivers/pull/119) require the use of the `MBED_HOSTTEST_RESULT(result)` macro.

However, in order to not have a dependency on mbed-drivers, [utest implements this manually](https://github.com/ARMmbed/utest/blob/master/source/default_handlers.cpp#L76), which then does not trigger the end of the coverage report.

See https://github.com/ARMmbed/mbed-drivers/issues/47 for information on moving `test_env.h` out of `mbed-drivers`.

**Comment by PrzemekWirkus** [comment]
I will work on this :)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2122
